title: Horizon Zero Waste
description: A simple guide to sustainable alternatives.
url: https://horizonzerowaste.com
logo: horizon-zero-waste.png
author:
  twitter: olivierlacan
plugins: 
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: horizon-zero-waste.png
